2025-10-21 15:26:46,243 - api_logger - INFO - Application startup.
2025-10-21 15:26:48,123 - api_logger - INFO - Application startup.
2025-10-21 15:26:51,223 - api_logger - INFO - Application startup.
2025-10-21 15:27:45,663 - api_logger - INFO - Application startup.
2025-10-21 15:29:05,329 - api_logger - INFO - Request: GET /docs
2025-10-21 15:29:05,331 - api_logger - INFO - Response: status_code=200
2025-10-21 15:29:05,459 - api_logger - INFO - Request: GET /openapi.json
2025-10-21 15:29:05,466 - api_logger - INFO - Response: status_code=200
2025-10-21 15:33:33,575 - api_logger - INFO - Request: POST /auth/register
2025-10-21 15:33:33,587 - api_logger - INFO - Attempting to register new user: user1@example.com
2025-10-21 15:38:49,284 - api_logger - INFO - Application startup.
2025-10-21 15:38:49,299 - api_logger - INFO - Default role 'user' created.
2025-10-21 15:38:50,698 - api_logger - INFO - Application startup.
2025-10-21 15:39:02,617 - api_logger - INFO - Application startup.
2025-10-21 15:39:04,005 - api_logger - INFO - Application startup.
2025-10-21 15:41:25,227 - api_logger - INFO - Application startup.
2025-10-21 15:41:27,763 - api_logger - INFO - Application startup.
2025-10-21 15:41:46,404 - api_logger - INFO - Request: GET /docs
2025-10-21 15:41:46,404 - api_logger - INFO - Response: status_code=200
2025-10-21 15:41:46,546 - api_logger - INFO - Request: GET /openapi.json
2025-10-21 15:41:46,553 - api_logger - INFO - Response: status_code=200
2025-10-21 15:45:33,519 - api_logger - INFO - Application startup.
2025-10-21 15:45:34,926 - api_logger - INFO - Application startup.
2025-10-21 15:45:45,127 - api_logger - INFO - Application startup.
2025-10-21 15:45:47,756 - api_logger - INFO - Request: GET /docs
2025-10-21 15:45:47,756 - api_logger - INFO - Response: status_code=200
2025-10-21 15:45:48,019 - api_logger - INFO - Request: GET /openapi.json
2025-10-21 15:45:48,025 - api_logger - INFO - Response: status_code=200
2025-10-21 15:45:59,229 - api_logger - INFO - Application startup.
2025-10-21 15:46:26,896 - api_logger - INFO - Application startup.
2025-10-21 15:46:37,371 - api_logger - INFO - Request: POST /auth/register
2025-10-21 15:46:37,374 - api_logger - INFO - Attempting to register new user: user_moi@example.com
2025-10-21 15:47:59,931 - api_logger - INFO - Application startup.
2025-10-21 15:48:01,952 - api_logger - INFO - Application startup.
2025-10-21 15:48:20,723 - api_logger - INFO - Application startup.
2025-10-21 15:48:23,618 - api_logger - INFO - Request: GET /docs
2025-10-21 15:48:23,619 - api_logger - INFO - Response: status_code=200
2025-10-21 15:48:23,754 - api_logger - INFO - Request: GET /openapi.json
2025-10-21 15:48:23,759 - api_logger - INFO - Response: status_code=200
2025-10-21 15:49:47,200 - api_logger - INFO - Request: POST /auth/register
2025-10-21 15:49:47,204 - api_logger - INFO - Attempting to register new user: user_moi@example.com
2025-10-21 15:49:47,762 - api_logger - INFO - User user_moi@example.com created successfully with ID 1.
2025-10-21 15:49:47,796 - api_logger - INFO - Response: status_code=201
2025-10-21 15:58:17,342 - api_logger - INFO - Application startup.
2025-10-21 15:58:18,703 - api_logger - INFO - Application startup.
2025-10-21 15:58:23,222 - api_logger - INFO - Application startup.
2025-10-21 15:58:24,572 - api_logger - INFO - Application startup.
2025-10-21 15:58:29,447 - api_logger - INFO - Application startup.
2025-10-21 15:58:30,800 - api_logger - INFO - Application startup.
2025-10-21 15:58:44,818 - api_logger - INFO - Application startup.
2025-10-21 15:58:47,964 - api_logger - INFO - Request: GET /docs
2025-10-21 15:58:47,965 - api_logger - INFO - Response: status_code=200
2025-10-21 15:58:48,109 - api_logger - INFO - Request: GET /openapi.json
2025-10-21 15:58:48,115 - api_logger - INFO - Response: status_code=200
2025-10-21 16:00:32,976 - api_logger - INFO - Request: POST /auth/register
2025-10-21 16:00:32,982 - api_logger - INFO - Attempting to register new user: user_moi@example.com
2025-10-21 16:00:32,986 - api_logger - WARNING - Registration failed: Email user_moi@example.com already registered.
2025-10-21 16:00:32,997 - api_logger - INFO - Response: status_code=400
2025-10-21 16:02:12,509 - api_logger - INFO - Application startup.
2025-10-21 16:02:15,752 - api_logger - INFO - Application startup.
2025-10-21 16:04:07,977 - api_logger - INFO - Application startup.
2025-10-21 16:05:30,626 - api_logger - INFO - Request: GET /docs
2025-10-21 16:05:30,626 - api_logger - INFO - Response: status_code=200
2025-10-21 16:05:30,763 - api_logger - INFO - Request: GET /openapi.json
2025-10-21 16:05:30,768 - api_logger - INFO - Response: status_code=200
2025-10-21 16:05:50,350 - api_logger - INFO - Application startup.
2025-10-21 16:05:51,726 - api_logger - INFO - Application startup.
2025-10-21 16:06:08,185 - api_logger - INFO - Request: GET /docs
2025-10-21 16:06:08,186 - api_logger - INFO - Response: status_code=200
2025-10-21 16:06:08,306 - api_logger - INFO - Request: GET /openapi.json
2025-10-21 16:06:08,310 - api_logger - INFO - Response: status_code=200
2025-10-21 16:06:44,125 - api_logger - INFO - Request: POST /auth/login
2025-10-21 16:06:44,127 - api_logger - INFO - Login attempt for user: user_moi@example.com
2025-10-21 16:06:44,671 - api_logger - INFO - User user_moi@example.com logged in successfully.
2025-10-21 16:06:44,673 - api_logger - INFO - Response: status_code=200
2025-10-23 12:50:52,824 - api_logger - INFO - Application startup.
2025-10-23 12:52:08,158 - api_logger - INFO - Request: GET /docs
2025-10-23 12:52:08,159 - api_logger - INFO - Response: status_code=200
2025-10-23 12:52:09,143 - api_logger - INFO - Request: GET /openapi.json
2025-10-23 12:52:09,149 - api_logger - INFO - Response: status_code=200
2025-10-23 12:53:35,638 - api_logger - INFO - Request: POST /auth/register
2025-10-23 12:53:35,641 - api_logger - INFO - Attempting to register new user: nghi
2025-10-23 12:53:36,088 - api_logger - INFO - User nghi created successfully with ID 2.
2025-10-23 12:53:36,255 - api_logger - ERROR - Traceback (most recent call last):
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\middleware\base.py", line 151, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\anyio\streams\memory.py", line 126, in receive
    raise EndOfStream from None
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HIEU\Downloads\DoAnLTANTT\DoAnLTANTT\app\main.py", line 38, in log_requests
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\fastapi\routing.py", line 123, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\fastapi\routing.py", line 109, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\fastapi\routing.py", line 409, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\fastapi\routing.py", line 252, in serialize_response
    raise ResponseValidationError(
        errors=_normalize_errors(errors), body=response_content
    )
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'value_error', 'loc': ('response', 'email'), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'nghi', 'ctx': {'reason': 'An email address must have an @-sign.'}}


2025-10-23 12:54:52,760 - api_logger - INFO - Request: POST /auth/login
2025-10-23 12:54:52,762 - api_logger - INFO - Login attempt for user: user_demo
2025-10-23 12:54:52,763 - api_logger - WARNING - Failed login attempt for user: user_demo
2025-10-23 12:54:52,765 - api_logger - INFO - Response: status_code=401
2025-10-23 12:59:33,472 - api_logger - INFO - Application startup.
2025-10-23 12:59:51,637 - api_logger - INFO - Request: POST /auth/register
2025-10-23 12:59:51,640 - api_logger - INFO - Attempting to register new user: user_demo
2025-10-23 12:59:52,074 - api_logger - INFO - User user_demo created successfully with ID 3.
2025-10-23 12:59:52,080 - api_logger - ERROR - Traceback (most recent call last):
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\middleware\base.py", line 151, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\anyio\streams\memory.py", line 126, in receive
    raise EndOfStream from None
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HIEU\Downloads\DoAnLTANTT\DoAnLTANTT\app\main.py", line 38, in log_requests
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\fastapi\routing.py", line 123, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\fastapi\routing.py", line 109, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\fastapi\routing.py", line 409, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\HIEU\AppData\Local\Programs\Python\Python313\Lib\site-packages\fastapi\routing.py", line 252, in serialize_response
    raise ResponseValidationError(
        errors=_normalize_errors(errors), body=response_content
    )
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'value_error', 'loc': ('response', 'email'), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'user_demo', 'ctx': {'reason': 'An email address must have an @-sign.'}}


